# Copyright (c) 2019, Peter Ohler, All rights reserved.

module BalanceBook
  module Model

    class Transaction < Base

      attr_accessor :id
      attr_accessor :credit # boolean
      attr_accessor :date
      attr_accessor :amount
      attr_accessor :who
      attr_accessor :account
      attr_accessor :currency
      attr_accessor :category
      attr_accessor :taxes # TaxAmount array
      attr_accessor :acctTrans
      attr_accessor :file
      attr_accessor :note

      def initialize(id)
	@id = id # generated by company to be unique
      end

      def tax
	return 0.0 if @taxes.nil?
	sum = 0.0
	@taxes.each { |ta| sum += ta.amount }
	sum
      end

      def validate(book)
	raise StandardError.new("Transaction ID can not be empty.") unless !@id.nil? && 0 < @id.size
	validate_date('Transaction date', @date)
	raise StandardError.new("Transaction amount of #{@amount} must be greater than 0.0.") unless 0.0 < @amount
	acct = book.company.find_account(@account)
	raise StandardError.new("Transaction account #{@account} not found.") if acct.nil?
	cat = book.company.find_category(@category)
	raise StandardError.new("Transaction category #{@category} not found.") if cat.nil?
	unless @acctTrans.nil?
	  raise StandardError.new("Account transaction #{@account}-#{@acctTrans} not found.") if acct.find_trans(@acctTrans).nil?
	end
      end

    end
  end
end
